# ----- FISHING ----- #
[fishing]
# Must be <= 1
base_catch_chance = 0.25
level_modifier = 0.10
experience = 10           # How much experience (fish caught) needed to level up

# Must add up to 100
[[fishing.fish]]
name = "Joel"
weight = 1
price = 10
chance = 50

[[fishing.fish]]
name = "Ricardo"
weight = 5
price = 50
chance = 25

[[fishing.fish]]
name = "Hector"
weight = 5
price = 100
chance = 15

[[fishing.fish]]
name = "Anna"
weight = 3
price = 500
chance = 5

[[fishing.fish]]
name = "Felix"
weight = 10
price = 750
chance = 4

[[fishing.fish]]
name = "Eduardo"
weight = 10
price = 1000
chance = 1

# Modifiers are multiplicative (example: final_catch_chance = base_catch_chance * (1 + modifier))
[[fishing.rod]]
name = "Crusty, Rusty, & Dusty"
price = 0
modifier = 0

[[fishing.rod]]
name = "Caster Lite"
price = 0
modifier = 0.10

[[fishing.bait]]
name = "Worm"
price = 1
modifier = 0.10

# ----- MODERATION ----- #
[moderation]
# Example: blacklisted_words = ["poop" "flip" "snap"]
blacklisted_words = []

# ----- TEXT TO SPEECH ----- $
[tts]

[tts.voice]
adam = "c4ad44ae-8da9-4375-90c0-55a1e6f1fbc6"
biden = "49826b97-091a-4821-a978-15692387647a"
obama = "9af5e3d0-b4b2-44eb-9580-849d8d36a30e"
spongebob = "faa92dd8-0517-49da-8f01-1fb03f0e0096"
squidward = "7cbd44df-08ac-4234-bc95-836e0ae6b22c"
forsen = "84cd0ca2-8b98-4fb7-9365-1c76965724d9"
asmr = "1aa9d694-1da5-4bdb-8e07-6392ec526c2f"
watchmojo = "237ba3de-73e0-4000-bd9a-f08c51ac5ef6"
linus = "e8a18685-00fd-4798-aa3d-50424f8de7e6"
kermit = "47906020-29e9-4903-91e3-8b66b0528410"
chills = "314df8f9-d157-4bb7-b744-0172e2fb8a32"
moist = "8312e7dd-cb15-4d9f-9d51-035209413b7a"
kawaii = "604168da-f156-450b-8794-e89175abdcd4"
plankton = "8153e703-4cfb-4716-8a92-ba19cc7f0228"
patrick = "7e0ee786-b660-47ce-8de7-02fd49698efc"
trump = "1948c544-0eab-4408-9259-567b5b2059a4"
gordon = "01f69a26-0759-44e4-b317-cdbcb26b26c0"
kronk = "172f01d8-32d7-4dba-850b-41f9bd9b2bbc"
shapiro = "a0741f38-b14a-4204-a26e-80f795f03637"
zoomer = "a5879188-842e-4971-a281-eae9791e2138"

# ----- VOICE ----- $
[voice]
play_cost = 0
tts_cost = 10
